$ErrorActionPreference='Stop'
$scratch=Join-Path $PSScriptRoot 'focused-evidence-438'
$destination=Join-Path $PSScriptRoot 'retained-438-01a11c7b/managed-438/focused-handoff'
$summary=Get-Content (Join-Path $scratch 'publication/summary.json') -Raw | ConvertFrom-Json
if($summary.head -ne '18cf84a2a4d5acc05ca14ecd2ddd861a1fe20b43' -or $summary.actualMaster -ne '547206a1b372b73fc95fc412ad453b8099440000') {throw 'Unexpected live source or target'}
if(@($summary.checks | Where-Object status -ne 'completed').Count) {throw 'CI remains pending'}
if(@($summary.checks | Where-Object conclusion -notin @('success','skipped')).Count) {throw 'CI requires disposition'}
$scope=Get-Content (Join-Path $PSScriptRoot 'retained-438-01a11c7b/managed-438/focused-followup/scope.json') -Raw | ConvertFrom-Json
$files=Get-Content (Join-Path $scratch 'publication/files.json') -Raw | ConvertFrom-Json
$commits=Get-Content (Join-Path $scratch 'publication/commits.json') -Raw | ConvertFrom-Json
$expectedParent=$summary.base
for($i=0;$i -lt $commits.Count;$i++) {
 if($commits[$i].sha -ne ($scope.commits[$i] -split ' ')[0] -or @($commits[$i].parents).Count -ne 1 -or $commits[$i].parents[0].sha -ne $expectedParent) {throw 'Published ordered commit ancestry differs'}
 $expectedParent=$commits[$i].sha
}
if(@(Compare-Object ($scope.files.file | Sort-Object) ($files.filename | Sort-Object)).Count) {throw 'Published scope differs'}
foreach($file in $files){$expected=$scope.files|Where-Object file -eq $file.filename;if($expected.added -ne $file.additions -or $expected.deleted -ne $file.deletions){throw ('Scope counts changed: '+$file.filename)}}
New-Item -ItemType Directory -Path $destination -Force | Out-Null
Copy-Item (Join-Path $scratch 'publication') (Join-Path $destination 'publication') -Recurse
foreach($name in @('final-mobile-ci.log','final-ci-watch.log','followup-public-readback.json','public-readback.json','pr459-status.json','remote-retention.txt')) {Copy-Item (Join-Path $scratch $name) (Join-Path $destination $name)}
Copy-Item (Join-Path $PSScriptRoot 'read-focused-publication.ps1') $destination
Copy-Item (Join-Path $PSScriptRoot 'package-focused-handoff.ps1') $destination
$handoff=@{
 checkedAt=[DateTime]::UtcNow.ToString('o');ownerTask='01a11c7b-b7fa-7578-9694-80a1cae2b03d';host='mchartier_zbook';repository='git@github.com:MChartier/calibrate-health.git';branch='fix/managed-first-438-focused';pullRequest=459;issue=438;headSha=$summary.head;baseSha=$summary.base;actualMasterSha=$summary.actualMaster;mergeBase='547206a1b372b73fc95fc412ad453b8099440000';headParent='6f7a1d9fa4dfbf69d3468114d33f4498cf577e03';parentRevisions=@();prBodySha256=$summary.bodySha256;issueBodySha256=$summary.issueBodySha256;draft=$summary.draft;scope=@{commits=$scope.commits;files=$scope.files;composition=$scope.composition;totals=$scope.totals;immutableRecord='https://github.com/MChartier/calibrate-health/blob/1f48682f47db90555f704637059fa2db0b8f4812/managed-438/focused-followup/scope.json';sha256='278a496129862c172acf42ae709d4f8dcd0351e7dc08207bc275cb330afe34cd'};
 standards=@{workflow='workflow-v3';communication='pr-review-v3';workflowCommit='f0919b184b6344d6279178b2388190936ca432a9';communicationCommit='97e5583c8355f3673aad0835c0ce3ca1486aeb8b';acknowledgment='Read full pinned sources and supplied amendments, including focused published-history scope, final-state concise communication, exact immutable provenance, quota-only bot exception, current issue/PR linkage, native deferral, rendering waiver, managed-first targeting, and one-writer/retention boundaries. No silent pin migration.'};
 evidence=@{captureCommit='19031ef5d6e23cdb66b24c839889082b9861a6ed';provenancePath='managed-438/focused-final/provenance.json';provenanceSha256='68f05781efd6ee208e96389b536cd2455a9a445ecf4996ef561f8e0b16a35eb2';manifestSha256='f0cbab9e0ef3bfa12caace6fa50d11bcfe2e3af552316fe0149181ab029ad9ee';followupCommit='1f48682f47db90555f704637059fa2db0b8f4812';applicabilitySha256='09284edc4d9d705c80f6aab7ae22731daf68593735fb66ee2e33a267edc47da4';publicByteChecks='82 original successor artifacts and 19 appended follow-up artifacts verified; receipts retained.';before='547206a1b372b73fc95fc412ad453b8099440000';after='8466b29695e6924db0ecbde0a435b04c49f56fc0';pairs=@('advanced','login','recovery','recovery-failure');sourceApplicability='Two native-only follow-ups do not change browser routes, build sources or fixture inputs; original captures are not relabeled.';pixelInspection='Author opened all eight genuine fresh PNGs. Independent QA inspection pending.';rendering='Actual GitHub-page rendering unexecuted under explicit human waiver.'};
 checks=@{ci=$summary.checks;passed=@($summary.checks|Where-Object conclusion -eq 'success').Count;skipped=@($summary.checks|Where-Object conclusion -eq 'skipped').Count;failed=0;pending=0;mobile='234 suites / 1347 tests passed on final head';apiClient='69 passed on final head';local='TypeScript, app config, 50 final storage/state tests, affected auth/workspace regressions, four maintained real-browser checks and four matched capture pairs per source passed.';expectedFailures='Three unchanged-master native remount regressions reproduced. Initial harness-resolution, wrong-cwd PWA tests, restricted-shell child-process failures, and rejected stale-cache export are retained as unsuccessful attempts, not passing evidence.';nativeDevice='Deferred and unexecuted; CI runtime bundles and debug/simulator builds are not device execution.'};
 feedback=@{quotaRefusal=@{commentId=6075059975;requestedRevision='6f7a1d9fa4dfbf69d3468114d33f4498cf577e03';text='You have reached your Codex usage limits for code reviews.';disposition='No completed current-head bot review; no retry or billing change. Independent engineering review/QA required under amendment6006523068.'};humanScope6072694319='Implemented accepted smaller design in a clean successor: direct removal, bounded storage gate and existing queues; no generic transition adapter, duplicate browser scheduler, backend auth protocol or workspace/outbox schema changes. Final product delta +20 lines; maintained regression delta +468; docs +1. Not claiming the overall diff shrinks.';priorR1='Native remount overwrite retains maintained fixes, with actual-master red reproduction and final-head regression pass. All predecessor receipts remain historical.';currentFeedback='Full current conversation, submitted reviews and inline comments read. No additional actionable current-head findings at final readback.'};
 retention=@{ref='refs/heads/evidence/managed-438-01a11c7b';owner='01a11c7b-b7fa-7578-9694-80a1cae2b03d';policy='Nonmerged evidence retention, no automatic deletion. Prior source/build/capture/harness identities preserved; no force-push or history erasure.';PR450=@{head='f417e84b430cc46275171462cc9d2373b8ee8f3e';state='open; coordinator decides closure after replacement verification'};PR439=@{head='ce8543483db55800034e6ed2622eeb4b9ac7f3b6';state='closed unmerged; original branch and deferred administrator/bootstrap scope retained'};PR402=@{head='a341dcf2e736c8207c7e9296c1c7a8f67cf012f5';state='closed unmerged; never reopened'};priorEvidenceTip='7751202f6c984f13f9c196d254cf5d2216cfc1ab'};
 linkage=@{nativeIssueAssociation='GitHub closingIssuesReferences confirms issue438';issueBody='Current implementing PR points to PR459; previous exact issue body retained before edit.';predecessorBacklink='PR450 comment6075063855';project='No Project fields changed; coordinator owns reconciliation.'};
 checkpoint=@{source='clean';evidence='committed and to be verified after push';state='idle after handoff';userActions=@();next='Same independent QA owner reviews final code/scope, behavior, genuine pixels and exact final body. Coordinator verifies before any readiness/closure action.';boundaries='No readiness label, ready-for-review, merge/automerge, deployment, credential/provisioning, release publication or installation.';progressTransport='Requested direct progress message to source thread returned thread not found; not retried. Normal trusted task-result delivery remains the handoff.'}
}
[IO.File]::WriteAllText((Join-Path $destination 'handoff.json'),($handoff|ConvertTo-Json -Depth 25))
$manifest=@(Get-ChildItem -LiteralPath $destination -Recurse -File | ForEach-Object {@{path=[IO.Path]::GetRelativePath($destination,$_.FullName).Replace('\','/');sha256=(Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash.ToLower()}})
[IO.File]::WriteAllText((Join-Path $destination 'manifest.json'),($manifest|ConvertTo-Json -Depth 5))
Write-Output ('Handoff body '+$summary.bodySha256+'; CI '+$handoff.checks.passed+' passed, '+$handoff.checks.skipped+' skipped.')
