import json,pathlib,hashlib,datetime
r=pathlib.Path('review458');d=json.loads((r/'prepublish.json').read_bytes());v=json.loads((r/'verification.json').read_bytes());old=json.loads((r/'initial.json').read_bytes())
for k in ['comments','reviews','inline','issueComments','bodySha256']:assert d[k]==old[k],k
assert d['pr']['head']['sha']==v['headSha'] and d['master']['sha']==v['baseSha']
v.update(schemaVersion=1,verdict='ready',workflowVersion='workflow-v3',prCommunicationStandard='pr-review-v3',workflowCommit='f0919b184b6344d6279178b2388190936ca432a9',reviewOverlayCommit='97e5583c8355f3673aad0835c0ce3ca1486aeb8b',pullRequest='https://github.com/MChartier/calibrate-health/pull/458',issue='https://github.com/MChartier/calibrate-health/issues/457',reviewerChat='01a11c7c-11db-70b8-ba73-efe3693b003e',implementationOwner='01a11db5-8540-740a-a673-1026c0b90007',host='MCHARTIER_ZBOOK',standardsAcknowledgment='Read full supplied execution/QA/common standards and all supplied direct amendments. Pins unchanged; one independent QA lane; owned isolated clone, no owner checkout edits.',checkedAtUtc=d['checkedAtUtc'],prBodySha256=d['bodySha256'],issueBodySha256=hashlib.sha256(d['issue']['body'].encode()).hexdigest(),supersedesVerdictCommentId=None,findings=[])
v['gates']={
'value':'Pass: explicitly admitted issue457 addresses observed token-created release-PR approval blocking and the reproduced smoke failure; bounded changes to existing workflows/helper/test/maintained guidance.',
'outcome':'Pass for source readiness: five existing read-only validation surfaces called with exact candidate/source SHAs; deterministic fixture; ordinary PR/manual selection preserved. No assertion of successful end-to-end release execution.',
'code':'Pass: inspected sole commit, all 12 changed files and relevant complete helpers/caller/callee contracts. No product logic, dependencies, lockfiles, release versions or new publication credentials changed.',
'engineeringReview':'Independent complete review performed by this trusted task. Historical same-account quota-only refusal6070781981 verified exactly; no current-head bot review/refusal or bot completion fabricated; no retry requested.',
'ci':'Pass: all five exact-head PR workflows successful;24 checks=11success/13 scope-selected platform skips. Actual populated-upgrade+goal smoke and rollback jobs passed. Ordinary-PR explicit release identity steps skipped honestly.',
'behavior':'Pass: 60 focused maintained tests independently passed; separate model with actual retained API metadata and skipped job names passes and rejects19 invalid cases. Inspected exact original red/final green local PostgreSQL logs and fresh hosted PostgreSQL15.19 complete smoke; expensive DB suite not duplicated.',
'evidence':'Pass: exact committed owner manifest and all12 artifacts verified, final record exact digest verified; original release/DB failures retained. Distinguish modeled trusted-run gate behavior from executed ordinary CI and real database reproduction.',
'communication':'Pass: concise base-state failure and final remedy first; scenario/expected/observed table establishes non-UI contracts, clearly discloses no trusted-release dispatch, PG environment differences, actionlint limitation and quota history. Issue uses fixed requirements/plan/task/PR format; native closingassociation457 verified.',
'stack':'Pass for current actual master only: one linear commit,12files,+520/-87; APIbase=actualmaster=mergebase=soleheadparent547206a1. No stacked parent. Overlap with PR441/452 explicitly disclosed; combined integration not certified.'}
v['analysis']={
'trust':'cut-release-handler verifies protected request/source and invokes local reusable cut-release. New validation calls depend on prepare,publish_candidate,release-validation. Each call grants only contents/pull-requests read, no secrets inheritance or environment; required downstream jobs have explicit candidate checkouts. Callee identity checks require full distinct candidate/source SHAs, sole parent, workflow SHA=source, GITHUB_SHA=source, master ref. Source candidate is already canonical-eight-mirror verified. Nested workflow permissions remain bounded by caller. Existing finalizer actions:read permits inventory reads; publication isolation unchanged.',
'resultBinding':'Both initial and immediately-premerge invocations supply current runID/attempt/workflowSHA. Gate binds API run repository,handler path,workflow_run event,master head/source,status,attempt, and exactly one referenced source identity for each required workflow. Complete pagination rejects truncation; per-job names bind candidate and surface; newest same-name execution wins, older same-run successes can satisfy failed-job retries. Required missing/failed/cancelled/neutral/skipped/unbound/wrongrun/wrongsource reject; only named platform/rollback skips allowed. Ref/run identity reread after inventory; SHA-locked merge and merge-parent/tree verification remain unchanged. Canonical candidate input prevents branch-based unchecked code reuse.',
'apiEvidenceLimits':'Retained original-release-run.json is real run37880190066 at547206a1 with matching handler/event/head/source and referenced_workflows schema. Original-build-jobs.json supplies real skipped names including literal matrix placeholder. New nested candidate jobs/names are modeled from checked workflow declarations, not claimed observed in a live release. Existing original nested handler jobs support name composition. No real workflow dispatch performed or required to fill this limit.',
'database':'Backdating formerly reselected a historical goal as latest. Current fixture captures intended latest ID before backdating, moves all other synthetic goals one day before scenario date, asserts intended active ID and reuses it across timezone/Wear/import cases. Expected84000/90000/87000/82000/81000 and receipt/sync/race invariants preserved. Prior immutable/history tests occur before synthetic rearrangement. Hosted complete smoke passes including later account-day changes; no production semantics or dependency changes.',
'selection':'Candidate build classification selects only release-config; migration rollback remains skipped for version-only candidate. Tests run both backend/mobile; container scan forces OS-only for release while weekly/manual library audit retained. New DB path filters cover goal/calorie/metric/user/import/watch/sync inputs; rollback filter remains migration-specific. Candidate concurrency includes runID/attempt and workflow-specific prefix; PR/manual groups unchanged.',
'scope':'All12paths map to issue457 workflow reuse/helper, fixture, maintained regression tests or maintained release guidance; no evidence archives or add/delete churn in the sole published commit.',
'project':'Read-only Project1 issue457 entry has Current PRs458 and verified implementation owner. Native GraphQL closingIssuesReferences contains457. PR itself has no Project item; issue item provides association. Board QA-queued wording is coordinator bookkeeping, no board completion certificate.',
'feedback':'Read all current issue457/PR458 comments, submitted reviews, inline comments and GraphQL reviewThreads; no unresolved actionable requests. Final pre/post-publication rereads required.'}
v['evidence']=[{'commitSha':'6bdfa677ae1b892d7cb147c2be7d271b896143d6','url':'https://github.com/MChartier/calibrate-health/blob/6bdfa677ae1b892d7cb147c2be7d271b896143d6/manifest.json','sha256':'b4741a77dd8b3e6a8e870bac00f67477f70711caec57b9487436d298404c37ba','assessment':'All12 listed exact blobs verified, including original failures and local red/green.'},{'commitSha':'ba3e7afa64f941d75295a9bc44a87f6ddf399097','url':'https://github.com/MChartier/calibrate-health/blob/ba3e7afa64f941d75295a9bc44a87f6ddf399097/final-record.json','sha256':'d64a6593f546f7bd417647e8838dbd1a411e69f7e04080415fa1b569800e8374'}]
v['uiEvidence']={'applicable':False,'nonUiObservableContract':'Release workflow exact-identity/fail-closed API decisions and real PostgreSQL fixture red/green; no changed application UI.','pairs':[],'provenanceRecords':[],'renderedPrInspection':{'observations':'No UI image contract; API-decoded final body read for human clarity. General human GitHub-rendering waiver acknowledged, no rendering pass claimed.'}}
v['limitations']=['No trusted release workflow dispatch, candidate455 rerun/edit, merge, tag, image/provider/OTA/deploy/device operation. Source readiness is not live operational success.','Ordinary PR CI does not execute release-input verification steps; maintained models and code inspection supply that bounded evidence.','Fresh independent checks:60maintained+19negative probes;160pass/2existing skips is verified retained author suite, not separately rerun. DB local WindowsPG16.14 retained author evidence; fresh actual CI logsPG15.19 independently inspected.','Raw actionlint1.7.12 unsupported existing job.workflow_sha/queue:max diagnostics are disclosed; no clean raw actionlint claim.','PR441/452 overlapping workflow/guidance/tests require coordinator-managed propagation/integration and affected QA; this verdict binds only current published458.','Historical bot quota refusal is not a completed review. No readiness,label,draft,Project or human approval mutation by QA.']
v['nextAction']='Coordinator separately save exact trusted comment receipt, recheck all live bindings/feedback/evidence and apply readiness policy if unchanged. Coordinate PR441/452 overlap separately. Reviewer is complete and idle; do not dispatch another QA without admission.'
(r/'verdict.json').write_bytes((json.dumps(v,indent=2)+'\n').encode())
(r/'README.md').write_text('# Independent PR458 readiness QA\n\nVerdict: ready for review at the exact head and actual master recorded in [verdict.json](verdict.json). One commit, 12 files; no blocking findings.\n\n60 focused tests pass independently. [Additional model](independent-probe.mjs) uses retained real API metadata/skipped names and rejects 19 invalid cases; it is not live release execution. [Detailed assessment](verdict.json) distinguishes hosted PostgreSQL CI, retained local red/green evidence, unchanged publication safeguards and integration limitations.\n\nAll original artifacts remain on their original immutable evidence commits; identities are recorded in identities.json and more-identities.json. All feedback, CI, issue/native and Project reads are retained. No source, issue/PR body, readiness, draft, Project, release or provider mutation.\n\nRetain this record without expiry on its dedicated nonmerged evidence ref. Owner: trusted QA task01a11c7c-11db-70b8-ba73-efe3693b003e.\n',encoding='utf-8')
print(json.dumps({k:v[k] for k in ['verdict','headSha','baseSha','prBodySha256','checkedAtUtc']}))
