import pathlib,json,hashlib,subprocess,base64,datetime
r=pathlib.Path(__file__).resolve().parent;c=r.parent/'calibrate-auth-qa'
def read(n):return json.loads((r/n).read_bytes())
def git(*a):return subprocess.check_output(['git',*a],cwd=c).decode().strip()
def blob(ref,p):return subprocess.check_output(['git','show',ref+':'+p],cwd=c).decode()
d=read('prepublish.json');i=read('initial.json');s=read('verification.json');old=json.loads((r.parent/'recheck441/verdict.json').read_bytes())
for k in ['comments','reviews','inline','issueComments','files','commits']:assert d[k]==i[k],k
assert d['pr']['body']==i['pr']['body'] and d['master']['sha']==s['baseSha'] and d['issue']['body']==i['issue']['body']
assert hashlib.sha256(d['issue']['body'].encode()).hexdigest()=='c39a1260f05bef4a1fbac83ac3954c0d0b352406864157d058270381021816aa'
assert d['bodySha256']=='b6cf507a7aeb82e436026cc9bf964bbc542740d0f3029a740450f0df2b49bb06'
assert 'tests 20' in (r/'gate-tests.log').read_text(encoding='utf-8-sig') and 'fail 0' in (r/'gate-tests.log').read_text(encoding='utf-8-sig')
refs=[s['headSha'],s['baseSha'],read('child452.json')['head']['sha'],read('candidate455.json')['head']['sha']]
consumers=[]
for ref in refs:
 text=blob(ref,'.github/workflows/cut-release.yml')
 first=text.split('      - name: Wait for exact release PR CI')[1].split('      - name: Merge the exact release pull request')[0]
 second=text.split('          # Re-read the complete CI inventory')[1].split('          MERGE_RESPONSE=')[0]
 consumers.append({'ref':ref,'waitStepSha256':hashlib.sha256(first.encode()).hexdigest(),'finalPremergeCallSha256':hashlib.sha256(second.encode()).hexdigest(),'twoCalls':text.count('node .release-tooling/scripts/release-ci-gate.mjs')})
assert len({x['waitStepSha256'] for x in consumers})==1 and len({x['finalPremergeCallSha256'] for x in consumers})==1 and all(x['twoCalls']==2 for x in consumers)
v={k:s[k] for k in ['headSha','baseSha','apiBaseSha','mergeBaseSha','ultimateTargetSha','headParents','targetParents','parentRevisions']}
v.update({'schemaVersion':1,'verdict':'ready','workflowVersion':'workflow-v3','prCommunicationStandard':'pr-review-v3','workflowCommit':'f0919b184b6344d6279178b2388190936ca432a9','reviewOverlay':'97e5583c8355f3673aad0835c0ce3ca1486aeb8b','reviewerChat':'01a11c7c-11db-70b8-ba73-efe3693b003e','host':'mchartier_zbook','pullRequest':'https://github.com/MChartier/calibrate-health/pull/441','issue':'https://github.com/MChartier/calibrate-health/issues/440','targetRepository':'MChartier/calibrate-health','targetRef':'master','checkedAtUtc':d['checkedAtUtc'],'supersedesVerdictCommentId':6071045718,'prBodySha256':d['bodySha256'],'issueBodySha256':hashlib.sha256(d['issue']['body'].encode()).hexdigest(),
'fullStandardsAcknowledgment':old['fullStandardsAcknowledgment'],
'scope':{'orderedCommits':[{'sha':x['sha'],'parents':[a['sha'] for a in x['parents']]} for x in d['commits']],'files':[{k:x[k] for k in ['filename','status','additions','deletions']} for x in d['files']],'additions':627,'deletions':785,'assessment':'Two scoped linear commits, 30 paths: product entrypoint/native CLI changes, four maintained regression files, maintained operator guides and package alias. Full live Git/API inventories reconcile without truncation; no evidence add/delete churn, unrelated parent merge or sibling commit in the published range. Source is identical to this lane previous full assessment.'},
'resolvedFindings':old['resolvedFindings']+[{'id':'C2','disposition':'resolved','evidence':'Current issue440 task section explicitly identifies approved replacement01a11db5-8540-740a-a673-1026c0b90007 and original01a114af-c6d1-705c-ade9-39553731d038 as history. Exact old body is suffix of archive6073919842; other issue sections unchanged. Native closing issue440 verified, no inline/review findings. Native owner read confirms completed441 handoff and separately active457; no competing441 writer.'}],
'findings':[],
'gates':{'value':'pass: approved bounded simplification of release choices and native build/submit commands; issue457 is separately scoped hands-off release repair.',
'outcome':'pass for issue440 entrypoint, recovery routing and preservation contract; does not certify end-to-end release operation or completion of issue457.',
'code':'pass: unchanged full two-commit range and original independently assessed code. Nine critical safeguards match actual master. Both CI gate consumers are unchanged across head/master/452/455; no weakened publication boundary.',
'engineeringReview':'pass under scoped quota-only exception6070781981 following6070780526 at current head. Historical completed review6032060810 remains bound to0c26cea. Full current issue/PR conversations, submitted reviews and inline threads reread; no actionable unresolved441 feedback.',
'ci':'pass for published head: five successful workflows,24 terminal checks (10success/14configured skips). Runs remain at their actual source/tested-base identities. This is not passing current-master release-candidate CI:455 approval failure and database failure are explicitly retained below.',
'behavior':'pass for bounded source contract:20 freshly executed focused CI-gate tests pass, including action_required, failure, missing/wholly skipped coverage, exact identity and final premerge checks. Historical routing/native source-import/mock evidence and117 original-reviewer tests remain applicable to unchanged441 code. New incoming goal-smoke failure is not relabeled as passed.',
'evidence':'pass: current impact/receipt8 exact blobs verified by GitSHA1/size/SHA256, given digests match; prior three exact comment receipts verified. Source-bound historical provenance retained; current raw failure logs inspected, with source relationship and test limits recorded.',
'communication':'pass: concise problem/solution and scenario-based expected/observed table accurately describe consolidation and fail-closed safeguards. Source/captured baseline, actual current target and historical tests are separated. The closing same-lane reassessment sentence is an accurate procedural requirement, not a claim that no QA ever occurred; no wording loop requested. Known457 operational failures are explicitly disclosed in this superseding verdict and linked evidence; the PR does not claim hands-off operation or a new integrated runtime pass.',
'stack':'pass for441 only: direct/ultimate master547206a1, API/source merge-base4cbcbc74, no stackedPR parent. Incoming14commits/37paths since merge-base (29paths since previous9dc0739 target) disjoint with441. Conflict probe preserves both sets exactly but is not runtime evidence. Child452 remains separate/unassessed.'},
'targetImpact':{'incomingCommits':s['incomingCommits'],'incomingPaths':s['incomingPaths'],'conflictProbe':s['conflictProbe'],'assessment':'Auth and completed-day/goal changes do not alter release request routing or native orchestration. tests.yml adds database-test environment only. However the incoming goal-pace smoke is required by database-upgrade.yml and has a real failed current-target candidate run; source disjointness alone is not a claim that the complete release pipeline passes.'},
'knownOperationalLimitation':{'issue':457,'candidatePr':455,'candidateHead':refs[3],'child452HeadReadOnly':refs[2],'sourceRelationship':s['releaseRelationship'],'exactConsumerComparisons':consumers,'observed':'Release run37880190066 job113658571223 failed at lint.yml action_required, identifying run37880437994. Database run37880437998 job113665062675 passed all48 migrations then failed scripts/postgres-goal-pace-smoke.mjs:279:24 with90000!=84000. Current master and455 smoke blobs match a1890cbb;441 and452 have historical961d595f. Gate helper blob e045505e is identical at all four sources; both premerge consumer snippets are identical.','relevance':'The merged441 chooser still calls the inherited PR-only gate. It therefore cannot deliver the newly requested hands-off release progression; current-master goal-smoke failure would also block release finalization. Gate safety works by refusing these states. This is an inherited operational defect, not introduced by441.','readinessDecision':'Does not block human review readiness of441 bounded consolidation: issue440 specifically preserves existing gate, bounded approval wait, retained candidates and failure rejection; changed routing/native behavior remains demonstrated. It DOES block treating441/452 as a hands-off release fix or authorizing an operational release retry. Issue457 must repair and validate these failures separately. No provider/settings workaround or455 mutation is authorized. If457 lands or changes shared workers, coordinator must invalidate affected base/behavior gates and request new impact QA.','fixtureDiagnosis':'Date-sensitive fixture suspected from source ordering and observed line279; no disposablePostgreSQL reproduction by this lane, no claim that all later timezone/Wear/import cases ran. Owner457 owns reproduction and correction.'},
'criticalUnchanged':s['criticalUnchanged'],'historicalReceipts':s['historicalReceipts'],'retainedOriginals':{**old['retainedOriginals'],'previousSameLaneVerdictCommit':'a73abd3d855fa653a50b02376699ff85ca48634a','previousSameLaneVerdictSha256':'4beff9e0dbcc9524f8ea95a5c20619c1e306a5f7b613a37261f12175a6e5f442','currentOwnerImpactCommit':'73c205a142ec34d8afc76413aa720d63a6a09ce9','currentOwnerReceiptCommit':'9e31053a081b66fe43be5091342c1167e5a1b063','previousPrBodySha256':old['prBodySha256'],'previousIssueBodySha256':old['issueBodySha256']},
'evidence':read('identities.json'),
'uiEvidence':{'applicable':False,'pairs':[],'nonUiObservableContract':'CLI/workflow request routing and mocked native worker ordering; no changed application UI. Exact-source original observations retained. Current focused CI gate fixture tests and real hosted failure logs establish fail-closed boundaries. No native device or screenshot/render result invented.'},
'tests':{'current':'node --test --test-isolation=none calibrate-auth-qa/scripts/release-ci-gate.test.mjs;20passed/0failed/0skipped','firstAttempt':'Default Node test runner failed before tests with spawn EPERM (-4048) in sandbox. Same maintained pure/mock suite ran in-process with --test-isolation=none; no ACL/sandbox change, no privileged retry, no external release call.','historical':'Original117 QA tests belong to reviewer01a1128e-30ca-76da-bdf8-6e588e957030. Owner154release/254native/26deployment tests and Linux CI results retain their original source identities; no broad repeat here.'},
'linkage':{'nativeClosingIssue':440,'currentTaskCorrect':True,'issueOriginalArchive':6073919842,'project':'No Project write or whole-board coverage certification; coordinator owns current Project reconciliation.'},
'limitations':['Readiness is limited to441 consolidation, not hands-off release readiness; issue457 remains active and unvalidated here.','No integrated runtime, disposable database, Docker, provider/release workflow, signing/upload/image/OTA/deployment or native device execution.','Child452 source identity inspected only for inheritance of gate; no child verdict or readiness.','No new user action required from this assessment; normal coordinator verification and human PR review remain.'],
'nextAction':'Coordinator separately persist exact comment receipt, reread full feedback/head/actual target/body/evidence and CI applicability before and after any readiness transition. Preserve issue457 operational blocker and separately queued child452. Any source/base/evidence drift requires affected reassessment.',
'checkpoint':'Complete and idle after receipt. One QA lane; no child task or suite started. Independent checkout clean; no source/body/Project/readiness/draft/merge changes.'})
(r/'verdict.json').write_bytes((json.dumps(v,indent=2)+'\n').encode());print('ready for bounded441 consolidation;457 remains operational blocker')
