import pathlib,json,hashlib,subprocess
r=pathlib.Path(__file__).resolve().parent;c=r.parent/'calibrate-auth-qa'
def read(n):return json.loads((r/n).read_bytes())
def sha(s):return hashlib.sha256(s.encode()).hexdigest()
d=read('prepublish.json');i=read('initial.json');s=read('verification.json');old=json.loads((r.parent/'recheck452/verdict.json').read_bytes());p=read('parent-current.json');parentVerdict=json.loads((r/'owner/49c1a587729372182e6629e0b4e5ca10548bb306/verdict.json').read_bytes())
for k in ['comments','reviews','inline','issueComments','commits','files']:assert d[k]==i[k],k+' changed'
assert d['pr']['body']==i['pr']['body'] and d['issue']['body']==i['issue']['body'] and d['master']['sha']==s['ultimateTargetSha']
assert d['bodySha256']=='f1e85ed295255d1b534f44f66d93548267637229c69efe9bca75387e6eda8945'
native=read('native.json')['data']['repository']['pullRequest'];assert native['closingIssuesReferences']['nodes']==[{'number':447}] and native['reviewThreads']['totalCount']==0
assert 'This association is nonclosing' in d['issue']['body'] and 'Refs #447.' in d['pr']['body']
gate=subprocess.check_output(['git','rev-parse',s['headSha']+':scripts/release-ci-gate.mjs'],cwd=c).decode().strip();assert gate=='e045505e34f52516e1fb3ea6dd3432edf87f4a1e'
def text(ref,path):return subprocess.check_output(['git','show',ref+':'+path],cwd=c).decode()
consumers=[]
for ref in [s['headSha'],s['baseSha'],s['ultimateTargetSha']]:
 t=text(ref,'.github/workflows/cut-release.yml');a=t.split('      - name: Wait for exact release PR CI')[1].split('      - name: Merge the exact release pull request')[0];b=t.split('          # Re-read the complete CI inventory')[1].split('          MERGE_RESPONSE=')[0];consumers.append({'ref':ref,'waitStepSha256':sha(a),'finalPremergeCallSha256':sha(b),'twoCalls':t.count('node .release-tooling/scripts/release-ci-gate.mjs')})
assert len({x['waitStepSha256'] for x in consumers})==len({x['finalPremergeCallSha256'] for x in consumers})==1 and all(x['twoCalls']==2 for x in consumers)
v={k:s[k] for k in ['headSha','baseSha','apiBaseSha','mergeBaseSha','ultimateTargetSha','ultimateMergeBaseSha','headParents','targetParents','ultimateTargetParents']}
v.update({'schemaVersion':1,'verdict':'changes-required','workflowVersion':'workflow-v3','prCommunicationStandard':'pr-review-v3','workflowCommit':'f0919b184b6344d6279178b2388190936ca432a9','communicationCommit':'97e5583c8355f3673aad0835c0ce3ca1486aeb8b','standardsAcknowledgment':'Entire supplied pinned QA role/common standards and direct amendments read and acknowledged; same unchanged execution/review pins. Current checkout AGENTS.md read in preceding parent assessment and byte-identical in child. Actual MCHARTIER_ZBOOK verified2026-10-09T04:53:32.4838420Z. Same trusted independent QA task; sole QA lane, no subordinate reviewer.','pullRequest':'https://github.com/MChartier/calibrate-health/pull/452','issue':'https://github.com/MChartier/calibrate-health/issues/447','targetRef':'mchartier/release-entrypoints-recovery','targetRepository':'MChartier/calibrate-health','reviewerChat':'01a11c7c-11db-70b8-ba73-efe3693b003e','host':'mchartier_zbook','checkedAtUtc':d['checkedAtUtc'],'supersedesVerdictCommentId':6071694756,'prBodySha256':d['bodySha256'],'issueBodySha256':sha(d['issue']['body']),'parentPrBodySha256':sha(p['pr']['body']),'parentIssueBodySha256':sha(p['issue']['body']),
'parentRevisions':[{'pr':441,'headSha':s['baseSha'],'sourceParentSha':s['apiBaseSha'],'actualTargetSha':s['ultimateTargetSha'],'apiBaseAndMergeBaseSha':s['ultimateMergeBaseSha'],'state':'open/unmerged, human-ready, nondraft at readback','verdictCommentId':6074437074,'verdictBodySha256':'aece9f33b5b73ca06ca84980d9e0eae2aaf0c5180c12ff8be44567dd5ac6f596','verdictUpdatedAt':'2026-10-09T04:44:53Z','prBodySha256':sha(p['pr']['body']),'gate':'Current parent receipt verified exactly; C2 resolved. Bounded consolidation readiness is not unattended-release certification.'}],
'findings':[{'id':'C3','priority':'P2','category':'metadata/communication','location':'issue447 Implementing PR section / PR452 native closing association','observed':'Issue body explicitly says This association is nonclosing, and PR body uses Refs #447. Fresh GraphQL closingIssuesReferences instead contains447. This is a native closing relationship, not merely the Project Current PR text field.','expected':'Primary issue narrative and actual native association must agree with the accepted preparation-only outcome.','scopeJudgment':'The accepted requirements authorize source/configuration/docs/tests and draft independent review. Provider execution, provisioning, signing, real IPA/TestFlight validation, rollout and deployment are explicitly outside447. Completing this preparation issue must not be presented as completing those excluded operations. A native closing link is not inherently wrong for a complete source-preparation issue; the current explicit nonclosing assertion is false.','ownerAction':'Coordinator or existing authorized issue metadata owner should preserve the exact current issue body, then replace the false nonclosing assertion with accurate wording that PR452 implements this preparation-only issue through the native linked PR and that release/provider validation, provisioning and rollout remain excluded/unperformed. If coordinator deliberately retains partial/nonclosing lifecycle semantics instead, remove the native closing edge and verify the supported association plus Project Current PR link. Do not change product source, broaden447, or request release execution. Return exact final issue body/native association for same-QA metadata-only recheck.','readinessImpact':'changes-required until this known contradiction is reconciled; no new human approval or product decision required.'}],
'resolvedFindings':[{'id':'R1','status':'resolved; unchanged','evidence':'50f4a845 and prior89-test/probe evidence verifies actual handler phases, retirement/tombstone/next allocation and rejection of provider intent.'},{'id':'R2','status':'resolved; unchanged','evidence':'50f4a845 puts production approval upstream of environment resolution and success-dependent export/intent/publication.'},{'id':'PARENT-C2','status':'resolved','evidence':'Current441 exact receipt6074437074 verified; parent issue440 now names approved replacement; readiness and nondraft states read back.'}],
'gates':{'value':'pass: accepted preparation-only selective release outcome, not permission to operate providers.',
'outcome':'pass for source-preparation requirements; C3 concerns inconsistent association wording only. Real provider/IPA/runtime provisioning excluded from accepted completion.',
'code':'pass: complete four ordered commits/parents and86 paths +6330/-110 independently reconcile with live API and Git; all prior assessed source blobs unchanged. No new source correction or test gap identified in this metadata/base continuation.',
'engineeringReview':'pass via independent complete-scope assessment and preserved R1/R2 dispositions. Bot6070337167 refused solely for quota at historicala8539c; no current-head completed bot review claimed. Full issue/PR comments, submitted reviews and inline threads reread, zero submitted reviews/threads.',
'ci':'pass for published source: five exact-head workflows remain successful,25 terminal checks (16success/9skipped). Historical tested base0c26cea retained; not integrated-runtime validation against547206a1. Existing raw actionlint remains nonclean with documented inherited/Cloud-feature diagnostics, not silently waived.',
'behavior':'pass for preparation using unchanged source-bound fixture/mock evidence and89 prior same-task tests. No new tests this metadata-only turn. The20 parent gate fixtures just executed in preceding441 assessment apply to byte-identical helper/test contract; do not certify provider behavior. Incoming backend runtime affects server input selection, not native/OTA input files. Conflict probes are not runtime execution.',
'evidence':'pass: five exact current/prior/parent retained artifacts verified by size/GitSHA1/SHA256; provided impact/receipt/verdict digests match. Prior negative and incomplete comment receipts verified unchanged. Historical source/build/fixture/CI/probe identities remain preserved; no relabeling as current-target execution.',
'communication':'changes-required forC3. PR problem/solution and behavioral table are readable and accurate for preparation, with parent/ultimate identities, actual versus historicalCI and unrun provider/native limitations distinguished. Issue requirements correctly bound preparation but nonclosing claim contradicts native state.',
'stack':'pass for current parent applicability: source/API/directmergebase0c26cea; actual441targetcd8932b2; ultimate547206a1; ultimateMB4cbcbc74. Parent gate cleared and receipt verified. Child remains unready forC3 only. PR450 separate dependency not imported;457 repair separate.'},
'publishedScope':{'commits':4,'files':86,'additions':6330,'deletions':110,'inventory':'verification.json / scope','rationale':'Product workflows and selective planner/recovery/provider-verification helpers, maintained tests, external build configuration/independent iOS allocation and maintained guide. No ad-hoc evidence/history churn; all four commits map to447 orR1/R2 corrections.'},
'targetImpact':{'sourceUnchangedFromPriorVerdict':True,'parentDelta':s['parentDelta'],'incomingSincePreviousUltimate':s['incoming29Paths'],'probes':s['probe'],'assessment':'Two parent documentation files and29 new ultimate-master auth/goal paths do not overlap child paths. Direct integrated child patch is byte-identical. Published head and prior89-test evidence unchanged. Earlier436 incoming source and its identities remain separately retained in prior assessment. New goal smoke failure remains a relevant inherited operational limitation below.'},
'inheritedReleaseLimitation':{'issue':457,'helperBlob':gate,'consumers':consumers,'copiedWorkflowPath':'.github/workflows/unified-server-handler.yml:83 invokes canonical cut-release.yml with selective:true; the two PR-only CI gates at child lines722/783 remain intact. Selective changes suppress downstream implicit work/cleanup; they do not supply a trusted non-PR candidate validation path.','observedFailures':parentVerdict['knownOperationalLimitation']['observed'],'relevance':'A selected server stage still encounters approval-required PR checks and current-master failing goal smoke. Those stop finalization as designed. This inherited limitation prevents claiming a working unattended release, but does not block the explicitly accepted fixture-validated preparation deliverable or require provider credentials. No blanket release waiver.','requiredFollowup':'Separate457 owner must correct and validate exact-candidate CI and deterministic smoke. Coordinate any shared worker/test/doc impact on441/452; a landed fix or target change requires new actual-range/applicability QA. Do not absorb work or mutate455/candidate/run.'},
'uiEvidence':old['uiEvidence'],'historicalTests':{'sameTask89':'recheck452/focused-tests.log, exact50f4a845; prior independent-probes.json establishesR1/R2. Retained23ba6e2 commit.','owner':'278pass/2existing skips;71focused, prior native/operations/Wear/deployment results retain original bindings.','thisTurn':'No fresh suite, capture, integrated runtime, provider or device execution. Appropriate for unchanged source and independently verified metadata/target impact.'},
'projectReadback':{'project':1,'title':'Agentic development pipeline','issueItemId':'PVTI_lAHOABMy1c4Bl3Eqzg_e1oE','currentPr':'https://github.com/MChartier/calibrate-health/pull/452','owner':'01a11cd8-3e02-703c-831c-fdc6176d7028','issueMembershipVerified':True,'directPrItemCount':0,'assessment':'Issue membership and Current PRs navigation are correct; no duplicate PR item needed. Pipeline Queued/Blocked by old parentC2 remains stale coordinator bookkeeping; reconcile to this C3 outcome, not a new user blocker. No writes or board-completion certificate.'},
'ownerCheckpoint':{'task':'01a11cd8-3e02-703c-831c-fdc6176d7028','turn':'01a11ef0-b9c6-7092-b53a-28e0d9bbcdfe','status':'completed/idle','branch':'mchartier/unified-release-447','sourceFrozen':True,'nativeRead':'Verified task status and final metadata-only handoff; original owner checkout untouched.'},
'historicalReceipts':s['historicalReceipts'],'retainedOriginals':{'negativeVerdictCommit':'b3ce696a170bd657e4e9f7715d7fc45f93b96c67','negativeVerdictSha256':'db170bc4c3ca143a12063801d51b5849ea9c8c879e3b902cffdd5983c4f3b69d','priorVerdictCommit':'23ba6e2ae1eba0289a0e61b734ed6889b5ae2cac','priorVerdictSha256':'480d94cf903d76d4a98f0441d46094585b7f23375fbebf253da9a1e9be01f489','originalBehaviorCommit':'80703680c484c534bcfa0f7ee18760870d2acc6f','correctionEvidenceCommit':'517fd4b8f69a67e6e7e50f251b656849efe05556','originalFinalReceiptCommit':'b46c78334ecc58c31cdd83602d172a0d2c1f05cc','policy':'All exact historical receipt/provenance identities preserved; no replacement or silent rebind.'},
'evidence':read('identities.json'),'limitations':['Preparation only; real IPA/provider validation, device checks and integrated runtime remain unperformed.','No release/provider/credential/protection/deployment or paid build operation.','Inherited457 remains operational blocker; parent readiness does not waive it.','C3 is an authorized metadata correction, not new approval. Coordinator owns Project/readiness/lifecycle.'],
'nextAction':'ReconcileC3 through existing coordinator/metadata owner, preserve exact issue body, read back native association and Current PR field, then same-task metadata-only QA. No source change or expensive suite rerun needed. Separate coordinator receipt and pre/post-readiness gates remain mandatory.',
'checkpoint':'Complete and idle after publication/readback; clean isolated source checkout, no local suite or provider operation, no next QA started.'})
(r/'verdict.json').write_bytes((json.dumps(v,indent=2)+'\n').encode());print(json.dumps({'verdict':v['verdict'],'finding':'C3 native closing vs nonclosing text','issueBodySha256':v['issueBodySha256'],'checks':s['checkSummary']}))
