export const PLAN_CHECK_RECOMMENDATION_STATUS = {
  generatedAt: '2026-07-31T20:00:00.000Z',
  inputFingerprint: 'current-input',
  planStatus: 'available',
  planReasonCode: null,
  evaluation: {
    modelVersion: 4,
    asOfDate: '2026-07-31',
    weightUnit: 'KG',
    status: 'recommendation',
    headline: "You're losing weight, but slower than planned",
    summary: 'Current evidence supports a lower calorie budget.',
    nextStep: null,
    historyProgress: null,
    selectedWindowDays: 28,
    dataQuality: {
      observationDays: 28,
      completeDays: 28,
      confidentDays: 28,
      suspiciousDays: 0,
      incompleteDays: 0,
      missingDays: 0,
      weightPoints: 14,
      weightSpanDays: 28,
    },
    missingCriteria: [],
    assumptions: [],
    estimates: {
      averageIntakeKcal: { low: 1825, midpoint: 1900, high: 1975 },
      observedWeeklyWeightChangeKg: { low: -0.4, midpoint: -0.36, high: -0.3 },
      targetAdjustmentKcal: { low: -250, midpoint: -200, high: -150 },
      configuredWeeklyWeightChangeKg: -0.455,
    },
    recommendation: {
      currentTargetKcal: 1900,
      recommendedTargetKcal: 1750,
      adjustmentStepKcal: -150,
      currentTargetAdjustmentKcal: 0,
      recommendedTargetAdjustmentKcal: -150,
    },
    activityContext: null,
    assessment: {
      version: 1,
      state: 'off_track',
      paceStatus: 'slower',
      window: {
        startDate: '2026-07-03',
        endDate: '2026-07-31',
        spanDays: 28,
        confidenceLevel: 0.95,
      },
      recentWeightTrendKgPerWeek: { low: -0.4, midpoint: -0.36, high: -0.3 },
      goalRateKgPerWeek: -0.455,
      blocker: null,
      targetDecision: 'change_available',
      targetDecisionBlocker: null,
      minimumDailyCalorieTargetKcal: 1650,
    },
  },
  recommendation: {
    id: 7,
    status: 'pending',
    inputFingerprint: 'current-input',
    effectiveLocalDate: '2026-08-01',
  },
  scheduledChange: null,
};
