const fs=require('fs'),path=require('path'),crypto=require('crypto'),{execFileSync}=require('child_process');
const root=process.cwd(),scratch=path.resolve(root,'../evidence-438-01a11c7b'),out=path.resolve(root,'../retained-438-01a11c7b/managed-438/r1-f417e84b');fs.mkdirSync(out,{recursive:true});
const hash=b=>crypto.createHash('sha256').update(b).digest('hex'),git=(...a)=>execFileSync('git',a,{cwd:root,encoding:'utf8'}).trim(),write=(f,v)=>fs.writeFileSync(path.join(out,f),JSON.stringify(v,null,2)+'\n');
for(const f of fs.readdirSync(scratch).filter(f=>/^after-r1-.*\.(png|json)$/.test(f)||/^r1-.*\.(log|patch|json)$/.test(f)))fs.copyFileSync(path.join(scratch,f),path.join(out,f));
fs.copyFileSync(__filename,path.join(out,'record-r1.cjs'));
function inventory(dir,prefix=''){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?inventory(path.join(dir,e.name),prefix+e.name+'/'):[{path:prefix+e.name,bytes:fs.statSync(path.join(dir,e.name)).size,sha256:hash(fs.readFileSync(path.join(dir,e.name)))}]);}
const head=git('rev-parse','HEAD'),target=git('rev-parse','origin/master'),base=git('merge-base',head,target),old=JSON.parse(fs.readFileSync(path.resolve(out,'../provenance.json'))),scope=JSON.parse(fs.readFileSync(path.resolve(out,'../checkpoint-60eca5e0/scope.json')));
scope.head=head;scope.actualTarget=target;scope.apiBase=base;scope.mergeBase=base;scope.headParents=git('show','-s','--format=%P',head).split(' ');scope.orderedCommits=git('rev-list','--reverse','--parents',target+'..'+head).split('\n');
scope.paths=git('diff','--name-status',target+'...'+head).split('\n').map(line=>{const [status,p]=line.split('\t');return{status,path:p,scope:scope.paths.find(x=>x.path===p)?.scope||(p.endsWith('test.ts')?'Maintained regression for cancelled native workspace persistence':'Guarded origin-scoped workspace persistence required by native provider isolation')}});
scope.totals={files:scope.paths.length,additions:0,deletions:0};for(const line of git('diff','--numstat',target+'...'+head).split('\n')){const[a,d]=line.split('\t');scope.totals.additions+=+a;scope.totals.deletions+=+d;}
scope.commitScopes.push({sha:head,scope:'QA R1 provider-lifetime invalidation, guarded token/workspace persistence and maintained remount/storage-failure regressions'});write('scope.json',scope);
write('target-impact.json',{head,target,apiBase:base,mergeBase:base,parentRevisions:[],incomingCommits:git('rev-list','--reverse','--parents',base+'..'+target).split('\n'),incomingPaths:git('diff','--name-status',base,target).split('\n'),patch:'r1-target.patch',patchSha256:hash(fs.readFileSync(path.join(out,'r1-target.patch'))),assessment:'Read complete PR436 incoming history and ten-file patch. Saved calorie comparisons/day/watch responses/sync, tests, API descriptions/generated comment and saved-target browser spec do not overlap any of this PR’s 38 paths, auth behavior, captured routes or fixture/harness. Original baseline remains representative for these states. No merge/rebase performed; no integrated-target build claimed.',conflictProbe:{command:'git merge-tree --write-tree HEAD origin/master',result:'clean',tree:'0f413d8f56bdfcce0ed5ff7df9e5c3f7f7a31d1b'}});
write('build-inventories.json',{after:inventory(path.join(root,'mobile/dist')),android:inventory(path.join(scratch,'r1-native-export'))});
const captures=['advanced','login','recovery','recovery-failure'].map(state=>{const f='after-r1-'+state+'.json';return{...JSON.parse(fs.readFileSync(path.join(out,f))),record:f,recordSha256:hash(fs.readFileSync(path.join(out,f)))}});
write('provenance.json',{...old,version:3,recordedAt:new Date().toISOString(),afterSource:head,actualTarget:target,apiBase:base,sourceClean:git('status','--porcelain')==='',baselineRecord:{commit:'a7d2ad1648d2b743cdfda5ef66950f6feee741ad',path:'managed-438/provenance.json',sha256:'08e3f6ec0867f9b28cc3141b1a8995c36eb4dddb7cd1631cad651bbe9c7c8dbd'},captures,commands:{...old.commands,capture:'CAPTURE_ROOT=<owned checkout> CAPTURE_LABEL=after-r1 node node_modules/@playwright/test/cli.js test --config ../evidence-438-01a11c7b/capture.config.cjs (four states)',native:'CI=1 EXPO_NO_TELEMETRY=1 node ../node_modules/expo/bin/cli export --platform android --output-dir ../../evidence-438-01a11c7b/r1-native-export (from mobile)'},harness:{commit:'a7d2ad1648d2b743cdfda5ef66950f6feee741ad',files:['capture.config.cjs','matched.spec.ts','fixture-used.ts'].map(f=>({path:'managed-438/'+f,sha256:hash(fs.readFileSync(path.resolve(out,'../'+f)))}))},baselineApplicability:'Baseline remains original independently built 4cbcbc74 capture, not relabeled to new actual master. Complete incoming target patch inspected: no affected capture/UI/auth inputs. See target-impact.json. Fresh After captures use exact clean f417e84 source.',authorPixelInspection:'Opened all four fresh PNGs: Advanced retains diagnostics/updates with hosting promotion absent; login has no destination field; reset and failed reset preserve their form and retry guidance. Independent QA must inspect the exact new captures. Identical unchanged-state image bytes come from independent captures.',testResults:{before:'Three new maintained remount tests fail on prior source; r1-before.log',localFull:'235 suites / 1341 tests passed before adding one final snapshot-restoration failure test',finalSnapshot:'All six offlineWorkspace tests passed including added failure recovery',typecheck:'passed on committed source',browser:'four maintained desktop/compact tests passed',capture:'four fresh genuine browser captures passed',webBuild:'passed clean committed source',android:'JavaScript export passed; no device execution'},qa:'R1 fix submitted for same independent QA; prior changes-required verdict remains historical and not silently replaced.'});
write('artifact-digests.json',fs.readdirSync(out,{withFileTypes:true}).filter(e=>e.isFile()&&e.name!=='artifact-digests.json').map(e=>({path:e.name,bytes:fs.statSync(path.join(out,e.name)).size,sha256:hash(fs.readFileSync(path.join(out,e.name)))})));
console.log(JSON.stringify({head,target,scope:scope.totals,provenanceSha256:hash(fs.readFileSync(path.join(out,'provenance.json')))}));
