const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto');
const harnessRoot=process.env.HARNESS_ROOT,sourceRoot=process.env.CAPTURE_SOURCE_ROOT;
const {test,expect,expectApiFailure,hideTransientPwaNotices}=require(path.join(harnessRoot,'e2e/expo-web/fixtures'));
const {installNotificationApi}=require(path.join(harnessRoot,'e2e/expo-web/notification-reminders.fixture'));
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
const git=(root,...args)=>cp.execFileSync('git',['-C',root,...args],{encoding:'utf8'}).trim();
const side=process.env.CAPTURE_SIDE,source=process.env.CAPTURE_SOURCE;
if(!['before','after'].includes(side)||git(sourceRoot,'rev-parse','HEAD')!==source||git(sourceRoot,'status','--porcelain'))throw Error('Unverified source');
const out=path.join(__dirname,'captures');fs.mkdirSync(out,{recursive:true});

async function setup(page,ux,{phone=false,empty=false}={}){
 const viewport=phone?{width:390,height:844}:{width:1440,height:1000};const theme=phone?'dark':'light';
 await page.setViewportSize(viewport);await page.emulateMedia({colorScheme:theme});
 const pending=[],served=[];
 page.on('response',r=>{const u=new URL(r.url());if(!/\.(js|css)$/.test(u.pathname)||!r.ok())return;pending.push((async()=>{const b=await r.body(),rel=decodeURIComponent(u.pathname).replace(/^\//,'');if(!b.equals(fs.readFileSync(path.join(sourceRoot,'mobile/dist',rel))))throw Error('Served export mismatch '+rel);served.push({path:rel,sha256:hash(b)});})());});
 await ux.install('populated');const fixture=await installNotificationApi(page,empty);
 let historyRequests=0;
 // The same fixture supplies baseline history compatibility; the final client must never request it.
 await page.route('**/api/v1/notifications/in-app?*',async route=>{if(new URL(route.request().url()).searchParams.get('view')!=='history')return route.fallback();historyRequests++;await route.fulfill({json:{notifications:fixture.history.slice(0,20),unread_count:empty?0:20,next_cursor:fixture.history.length>20?'after-104':null}});});
 const ready=async()=>{await hideTransientPwaNotices(page);await expect.poll(()=>page.evaluate(()=>document.documentElement.style.colorScheme)).toBe(theme);await page.evaluate(()=>document.fonts.ready);};
 const capture=async(name,observation={})=>{await ready();await Promise.all(pending);const image=side+'-'+name+'.png';const b=await page.screenshot({path:path.join(out,image),animations:'disabled'});const record={name,side,source,sourceTree:git(sourceRoot,'rev-parse','HEAD^{tree}'),harnessSource:git(harnessRoot,'rev-parse','HEAD'),sourceClean:true,capturedAtUtc:new Date().toISOString(),browser:page.context().browser().version(),host:require('node:os').hostname(),viewport,theme,scale:1,locale:'en-US',timezone:'America/Los_Angeles',clock:'2026-07-21T19:00:00.000Z',reducedMotion:'reduce',serviceWorkers:'block',normalization:'Same synthetic fixtures and transient PWA-notice suppression on both sides; actual compared UI unaltered. Unedited viewport screenshot.',route:new URL(page.url()).pathname,historyRequests,actionRequests:fixture.actionRequests,observation,image,imageSha256:hash(b),servedAssets:[...new Map(served.map(a=>[a.path,a])).values()].sort((a,b)=>a.path.localeCompare(b.path)),captureHarnessSha256:hash(fs.readFileSync(__filename)),captureConfigSha256:hash(fs.readFileSync(path.join(__dirname,'capture.config.cjs')))};fs.writeFileSync(path.join(out,side+'-'+name+'.json'),JSON.stringify(record,null,2)+'\n');};
 const open=async()=>{await ready();await page.getByRole('button',{name:/^Open notifications/}).click();const panel=page.getByRole('dialog',{name:'Notifications',exact:true});await expect(panel).toBeVisible();await expect.poll(()=>panel.evaluate(el=>Math.round(el.getBoundingClientRect().right))).toBe(viewport.width);return panel;};
 return{fixture,capture,ready,open};
}

test('empty drawer',async({page,ux})=>{const c=await setup(page,ux,{empty:true});await page.goto('/today');const panel=await c.open();await expect(panel.getByText('All caught up',{exact:true})).toBeVisible();await expect(panel.getByTestId('view-all-notifications')).toHaveCount(side==='before'?1:0);await c.capture('empty-desktop',{state:'empty reminders',expectedFooter:side==='before'});});
test('removed notifications address',async({page,ux})=>{const c=await setup(page,ux);if(side==='after')expectApiFailure(page,{method:'GET',pathname:'/notifications',status:404});await page.goto('/notifications?legacy=1#archive');await c.ready();if(side==='before'){await expect(page.getByTestId('notification-history-list')).toBeVisible();await expect(page.getByRole('heading',{name:'Notification history',exact:true})).toBeVisible();}else{await expect(page).toHaveURL(u=>u.pathname==='/today'&&!u.search&&!u.hash);await expect(page.getByRole('heading',{name:'Daily balance',exact:true})).toBeVisible();await expect(page.getByTestId('notification-history')).toHaveCount(0);}await c.capture('removed-address-desktop',{requestedRoute:'/notifications?legacy=1#archive',expectedRoute:side==='before'?'/notifications':'/today',mechanism:side==='before'?'Existing history screen':'No notifications route or alias; generic unknown-route fallback'});});

test('general unknown address',async({page,ux})=>{const c=await setup(page,ux);expectApiFailure(page,{method:'GET',pathname:'/missing/deep/page',status:404});await page.goto('/missing/deep/page?old=1#section');await c.ready();if(side==='before'){await expect(page.getByRole('heading',{name:'Page not found',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Go to Today',exact:true})).toBeVisible();}else{await expect(page).toHaveURL(u=>u.pathname==='/today'&&!u.search&&!u.hash);await expect(page.getByRole('heading',{name:'Daily balance',exact:true})).toBeVisible();}await c.capture('unknown-address-desktop',{requestedRoute:'/missing/deep/page?old=1#section',expectedRoute:side==='before'?'/missing/deep/page':'/today',mechanism:side==='before'?'Manual not-found recovery':'Automatic generic replacement to protected Today'});});
