import { test, expect, hideTransientPwaNotices, activateFixtureOffline, expectApiFailure } from '../quantity-448/e2e/expo-web/fixtures';
import { writeFile } from 'node:fs/promises';

const food={id:901,type:'FOOD',name:'Synthetic quarter-cup oats',serving_size_quantity:0.25,serving_unit_label:'cup',calories_per_serving:100,is_pinned:false};
const initial={id:701,name:'Synthetic existing oats',meal_period:'BREAKFAST',calories:100,servings_consumed:1,serving_size_quantity_snapshot:0.25,serving_unit_label_snapshot:'cup',calories_per_serving_snapshot:100,grams_per_measure_snapshot:20,grams_total_snapshot:20};
async function setup(page:any,ux:any) {
  await ux.install('populated',{foodEntries:[initial]});
  const rows:any[]=[{...initial}];const traffic:any[]=[];const dedup=new Map();let fail=false;let loseAck=false;let nextId=702;
  await page.addInitScript(()=>{(window as any).__quantityEvents=[];for(const type of ['focusin','focusout','input','change','pointerdown','click'])document.addEventListener(type,(e:any)=>{const t=e.target;if(t instanceof HTMLInputElement || t.closest?.('[role=button]'))(window as any).__quantityEvents.push({type,value:t.value,label:t.getAttribute?.('aria-label'),text:t.closest?.('[role=button]')?.textContent});},true);});
  await page.route('**/api/v1/my-foods*',route=>route.fulfill({json:new URL(route.request().url()).pathname.endsWith('/library')?{items:[food],next_cursor:null}:[food]}));
  await page.route('**/api/v1/food/search?*',route=>route.fulfill({json:{items:[],provider:'usda'}}));
  await page.route(/\/api\/v1\/food(?:\?|\/\d+|$)/,async route=>{
    const req=route.request();const method=req.method();if(method==='GET')return route.fulfill({json:rows});
    const payload=req.postDataJSON();const key=req.headers()['x-client-operation-id']??payload.operation_id;
    if(fail){traffic.push({method,payload,key,status:503});return route.fulfill({status:503,json:{error:'Synthetic outage',retryable:true}});}
    let result=dedup.get(key);if(!result){
      if(method==='POST') {result={...initial,...payload,id:nextId++,name:food.name,serving_size_quantity_snapshot:food.serving_size_quantity,serving_unit_label_snapshot:food.serving_unit_label,calories:Math.round(payload.servings_consumed*100),grams_total_snapshot:payload.servings_consumed*20};rows.push(result);}
      else {result=rows.find(r=>r.id===Number(new URL(req.url()).pathname.split('/').pop()));Object.assign(result,payload);result.calories=Math.round(result.servings_consumed*100);result.grams_total_snapshot=result.servings_consumed*20;}
      if(key)dedup.set(key,result);
    }
    if(loseAck){traffic.push({method,payload,key,status:503,committed:true});return route.fulfill({status:503,json:{error:'Synthetic lost acknowledgement after commit',retryable:true}});}traffic.push({method,payload,key,status:method==='POST'?201:200,response:{...result}});await route.fulfill({status:method==='POST'?201:200,json:result});
  });
  await page.goto('/food-log');await hideTransientPwaNotices(page);await expect(page.getByRole('button',{name:'Edit Synthetic existing oats',exact:true})).toBeVisible();
  return {rows,traffic,setFail:(v:boolean)=>fail=v,setAck:(v:boolean)=>loseAck=v};
}
async function edit(page:any,name=initial.name){await page.getByRole('button',{name:`Edit ${name}`,exact:true}).click();return page.getByRole('dialog',{name:'Edit food',exact:true});}
async function add(page:any){await page.getByRole('button',{name:'Add food',exact:true}).click();const d=page.getByRole('dialog',{name:'Add food',exact:true});await d.getByRole('radio',{name:'Search',exact:true}).click();await d.getByLabel('Search foods').fill(food.name);await d.getByText(food.name,{exact:true}).click();return d;}
async function saveEvidence(page:any,info:any,record:any){record.events=await page.evaluate(()=>(window as any).__quantityEvents);record.browser=page.context().browser().version();await writeFile(info.outputPath('observations.json'),JSON.stringify(record,null,2));}

for(const text of ['0.125','1.3','1,3']) for(const mode of ['immediate','blur']) {
 test(`existing ${text.replace(',', 'comma')} ${mode}`,async({page,ux},info)=>{const state=await setup(page,ux);let d=await edit(page);const input=d.getByRole('textbox',{name:'Amount',exact:true});await input.fill(text);if(mode==='blur')await input.press('Tab');await d.getByRole('button',{name:'Save',exact:true}).click();await expect(d).toBeHidden();expect(state.traffic[0].payload.servings_consumed).toBe(Number(text.replace(',','.'))/0.25);(state as any).eventsBeforeReload=await page.evaluate(()=>(window as any).__quantityEvents);await page.reload();await hideTransientPwaNotices(page);d=await edit(page);await expect(d.getByRole('textbox',{name:'Amount',exact:true})).toHaveValue(text.replace(',','.'));await saveEvidence(page,info,state);});
 test(`add ${text.replace(',', 'comma')} ${mode}`,async({page,ux},info)=>{const state=await setup(page,ux);const d=await add(page);const input=d.getByRole('textbox',{name:'Amount',exact:true});await input.fill(text);if(mode==='blur')await input.press('Tab');await d.getByRole('button',{name:'Add & close',exact:true}).click();await expect(d).toBeHidden();expect(state.traffic[0].payload.servings_consumed).toBe(Number(text.replace(',','.')));(state as any).eventsBeforeReload=await page.evaluate(()=>(window as any).__quantityEvents);await page.reload();await hideTransientPwaNotices(page);const e=await edit(page,food.name);await expect(e.getByRole('textbox',{name:'Amount',exact:true})).toHaveValue(String(Number(text.replace(',','.'))*0.25));await saveEvidence(page,info,state);});
}

test('validation, button increment, six-place edit boundary',async({page,ux},info)=>{const state=await setup(page,ux);let d=await edit(page);const input=d.getByRole('textbox',{name:'Amount',exact:true});for(const v of ['', 'invalid','0','-1']){await input.fill(v);await d.getByRole('button',{name:'Save',exact:true}).click();await expect(d.getByRole('alert')).toContainText('Amount must be a positive number');expect(state.traffic).toHaveLength(0);}await input.fill('0.125');await d.getByRole('button',{name:'Increase Amount by 0.25',exact:true}).click();await expect(input).toHaveValue('0.375');await d.getByRole('button',{name:'Decrease Amount by 0.25',exact:true}).click();await expect(input).toHaveValue('0.125');await input.fill('0.250001');await d.getByRole('button',{name:'Save',exact:true}).click();await expect(d).toBeHidden();await saveEvidence(page,info,state);});

test('offline add and edit replay retain decimals and identities',async({page,ux},info)=>{const state=await setup(page,ux);state.setFail(true);expectApiFailure(page,{method:'POST',pathname:'/api/v1/food',status:503});expectApiFailure(page,{method:'PATCH',pathname:'/api/v1/food/701',status:503});let d=await add(page);await d.getByRole('textbox',{name:'Amount',exact:true}).fill('0.125');await d.getByRole('button',{name:'Add & close',exact:true}).click();await expect(d).toBeHidden();d=await edit(page);await d.getByRole('textbox',{name:'Amount',exact:true}).fill('1,3');await d.getByRole('button',{name:'Save',exact:true}).click();await expect(d).toBeHidden();const queued=await page.evaluate(()=>new Promise<any[]>((resolve,reject)=>{const open=indexedDB.open('calibrate-offline');open.onsuccess=()=>{const db=open.result;const r=db.transaction('queued_mutations').objectStore('queued_mutations').getAll();r.onsuccess=()=>{resolve(r.result);db.close()};r.onerror=()=>reject(r.error)};open.onerror=()=>reject(open.error)}));expect(queued).toHaveLength(2);await page.reload();await hideTransientPwaNotices(page);state.setFail(false);await activateFixtureOffline(page);await page.context().setOffline(false);await expect.poll(()=>state.rows.length).toBe(2);await expect.poll(()=>state.rows[0].servings_consumed).toBe(5.2);expect(state.rows[1].servings_consumed).toBe(0.125);await saveEvidence(page,info,{...state,queued});});

test('observed one-millionth edit is omitted from request',async({page,ux},info)=>{
 const state=await setup(page,ux);let d=await edit(page);let input=d.getByRole('textbox',{name:'Amount',exact:true});await input.fill('0.250001');await expect(input).toHaveValue('0.250001');await page.screenshot({path:info.outputPath('typed.png')});await d.getByRole('button',{name:'Save',exact:true}).click();await expect(d).toBeHidden();const saveEvents=await page.evaluate(()=>(window as any).__quantityEvents);expect(state.traffic[0].payload).not.toHaveProperty('servings_consumed');await page.reload();await hideTransientPwaNotices(page);d=await edit(page);input=d.getByRole('textbox',{name:'Amount',exact:true});await expect(input).toHaveValue('0.25');await page.screenshot({path:info.outputPath('reopened.png')});await saveEvidence(page,info,{...state,typed:'0.250001',reopened:await input.inputValue(),saveEvents});
});

for(const flow of ['edit','add'])test(`simulated visual viewport shrink ${flow}`,async({page,ux},info)=>{
 const state=await setup(page,ux);const d=flow==='edit'?await edit(page):await add(page);const input=d.getByRole('textbox',{name:'Amount',exact:true});await input.fill('0.125');await input.focus();await page.evaluate(()=>{Object.defineProperty(window.visualViewport,'height',{configurable:true,get:()=>420});window.visualViewport!.dispatchEvent(new Event('resize'));});
 await expect.poll(async()=>{const b=await input.boundingBox();return b!.y+b!.height}).toBeLessThanOrEqual(420);const focusedBox=await input.boundingBox();await page.screenshot({path:info.outputPath('viewport-simulation.png')});const button=d.getByRole('button',{name:flow==='edit'?'Save':'Add & close',exact:true});await button.scrollIntoViewIfNeeded();const buttonBox=await button.boundingBox();expect(buttonBox!.y+buttonBox!.height).toBeLessThanOrEqual(420);await button.click();await expect(d).toBeHidden();await saveEvidence(page,info,{...state,simulation:'visualViewport.height=420, layout viewport 390x844; not native keyboard',focusedBox,buttonBox});
});

test('short browser window clips add editor independently of viewport mocking',async({page,ux},info)=>{
 const state=await setup(page,ux);const d=await add(page);const input=d.getByRole('textbox',{name:'Amount',exact:true});await input.fill('0.125');await page.setViewportSize({width:390,height:420});await input.focus();
 const geometry=await input.evaluate((el:HTMLElement)=>{const parents=[];let p:HTMLElement|null=el;while(p){const r=p.getBoundingClientRect();const s=getComputedStyle(p);parents.push({tag:p.tagName,testid:p.getAttribute('data-testid'),rect:{x:r.x,y:r.y,width:r.width,height:r.height},overflow:s.overflow,flex:s.flex,scrollHeight:p.scrollHeight,scrollTop:p.scrollTop});p=p.parentElement;}return {active:document.activeElement===el,parents,innerHeight,visualHeight:visualViewport?.height};});
 await page.screenshot({path:info.outputPath('short-window.png')});await saveEvidence(page,info,{...state,geometry});expect(geometry.parents[0].rect.y+geometry.parents[0].rect.height).toBeGreaterThan(420);
});

test('committed add with lost acknowledgement replays same identity once',async({page,ux},info)=>{
 const state=await setup(page,ux);state.setAck(true);expectApiFailure(page,{method:'POST',pathname:'/api/v1/food',status:503});const d=await add(page);await d.getByRole('textbox',{name:'Amount',exact:true}).fill('0.125');await d.getByRole('button',{name:'Add & close',exact:true}).click();await expect(d).toBeHidden();await expect.poll(()=>state.traffic.length).toBeGreaterThan(0);expect(state.rows).toHaveLength(2);await page.reload();await hideTransientPwaNotices(page);state.setAck(false);await activateFixtureOffline(page);await page.context().setOffline(false);await expect.poll(()=>state.traffic.some(t=>t.status===201)).toBe(true);expect(state.rows).toHaveLength(2);expect(new Set(state.traffic.map(t=>t.key)).size).toBe(1);expect(state.traffic[0].key).toMatch(/^[0-9a-f-]{36}$/);expect(state.rows[1].servings_consumed).toBe(0.125);await saveEvidence(page,info,state);
});

test('add invalid quantities stay unsaved and step buttons preserve typed precision',async({page,ux},info)=>{
 const state=await setup(page,ux);const d=await add(page);const input=d.getByRole('textbox',{name:'Amount',exact:true});for(const value of ['', 'invalid','0','-1']){await input.fill(value);await expect(d.getByRole('button',{name:'Add & close',exact:true})).toBeDisabled();await expect(d.getByRole('alert')).toBeVisible();expect(state.traffic).toHaveLength(0);}await input.fill('0.125');await d.getByRole('button',{name:'Increase Amount by 0.25',exact:true}).click();await expect(input).toHaveValue('0.375');await d.getByRole('button',{name:'Decrease Amount by 0.25',exact:true}).click();await expect(input).toHaveValue('0.125');await d.getByRole('button',{name:'Add & close',exact:true}).click();await expect(d).toBeHidden();expect(state.traffic[0].payload.servings_consumed).toBe(0.125);await saveEvidence(page,info,state);
});


