/**
 * Cross-platform visual identity for Calibrate.
 *
 * Platform layers translate these semantic roles into MUI or React Native
 * component themes. Keeping raw component styling out of this module lets the
 * web and native apps share a brand without forcing identical layouts.
 */
export const calibrateDesignTokens = {
    brand: {
        ink: '#1F2937',
        green: '#2E7D32',
        greenDark: '#1B5E20',
        amber: '#F59E0B'
    },
    schemes: {
        light: {
            background: '#F6F8F4',
            surface: '#FFFFFF',
            surfaceContainerLow: '#F9FBF7',
            surfaceContainer: '#EEF3EA',
            surfaceContainerHigh: '#E5ECE1',
            surfaceHovered: '#F1F5EE',
            surfacePressed: '#DCE7D7',
            onBackground: '#182019',
            onSurface: '#1F2937',
            onSurfaceVariant: '#526057',
            outline: '#7D8B7D',
            outlineVariant: '#CDD7C9',
            primary: '#2E7D32',
            onPrimary: '#FFFFFF',
            primaryContainer: '#D8EFD6',
            onPrimaryContainer: '#17491B',
            focusRing: '#2457A7',
            neutralEmphasis: '#526057',
            onNeutralEmphasis: '#FFFFFF',
            neutralEmphasisContainer: '#E5ECE1',
            onNeutralEmphasisContainer: '#1F2937',
            selection: '#526057',
            onSelection: '#FFFFFF',
            selectionContainer: '#E5ECE1',
            onSelectionContainer: '#1F2937',
            info: '#2457A7',
            onInfo: '#FFFFFF',
            infoContainer: '#E5EEFF',
            onInfoContainer: '#123B75',
            success: '#2E7D32',
            onSuccess: '#FFFFFF',
            successContainer: '#D8EFD6',
            onSuccessContainer: '#17491B',
            positive: '#2E7D32',
            onPositive: '#FFFFFF',
            positiveContainer: '#D8EFD6',
            onPositiveContainer: '#17491B',
            warning: '#B45309',
            onWarning: '#FFFFFF',
            warningAccent: '#F59E0B',
            warningContainer: '#FFF1D6',
            onWarningContainer: '#713A00',
            caution: '#B45309',
            onCaution: '#FFFFFF',
            cautionContainer: '#FFF1D6',
            onCautionContainer: '#713A00',
            danger: '#BA1A1A',
            onDanger: '#FFFFFF',
            dangerContainer: '#FFDAD6',
            onDangerContainer: '#93000A',
            celebration: '#6B4EFF',
            onCelebration: '#FFFFFF',
            celebrationContainer: '#EEE9FF',
            onCelebrationContainer: '#32206F',
            scrim: 'rgba(11, 18, 12, 0.48)',
            ripple: 'rgba(46, 125, 50, 0.16)'
        },
        dark: {
            background: '#0E1510',
            surface: '#151D17',
            surfaceContainerLow: '#18211A',
            surfaceContainer: '#1D2820',
            surfaceContainerHigh: '#27342A',
            surfaceHovered: '#222F25',
            surfacePressed: '#344538',
            onBackground: '#E3EAE1',
            onSurface: '#E3EAE1',
            onSurfaceVariant: '#BCCABC',
            outline: '#899789',
            outlineVariant: '#3D4A3E',
            primary: '#8DD990',
            onPrimary: '#00390A',
            primaryContainer: '#14521C',
            onPrimaryContainer: '#A8F5A8',
            focusRing: '#ADC7FF',
            neutralEmphasis: '#BCCABC',
            onNeutralEmphasis: '#18211A',
            neutralEmphasisContainer: '#3D4A3E',
            onNeutralEmphasisContainer: '#E3EAE1',
            selection: '#BCCABC',
            onSelection: '#18211A',
            selectionContainer: '#3D4A3E',
            onSelectionContainer: '#E3EAE1',
            info: '#ADC7FF',
            onInfo: '#002E69',
            infoContainer: '#173F75',
            onInfoContainer: '#D8E2FF',
            success: '#8DD990',
            onSuccess: '#00390A',
            successContainer: '#14521C',
            onSuccessContainer: '#A8F5A8',
            positive: '#8DD990',
            onPositive: '#00390A',
            positiveContainer: '#14521C',
            onPositiveContainer: '#A8F5A8',
            warning: '#FFB95C',
            onWarning: '#432B00',
            warningAccent: '#FFB95C',
            warningContainer: '#633F00',
            onWarningContainer: '#FFDEA6',
            caution: '#FFB95C',
            onCaution: '#432B00',
            cautionContainer: '#633F00',
            onCautionContainer: '#FFDEA6',
            danger: '#FF5F56',
            onDanger: '#210101',
            dangerContainer: '#5C1717',
            onDangerContainer: '#FFE2DE',
            celebration: '#D1C2FF',
            onCelebration: '#2B165C',
            celebrationContainer: '#4B3588',
            onCelebrationContainer: '#F0EAFF',
            scrim: 'rgba(0, 0, 0, 0.64)',
            ripple: 'rgba(141, 217, 144, 0.20)'
        }
    },
    typography: {
        page: { fontSize: 24, lineHeight: 30, fontWeight: '700', letterSpacing: -0.2 },
        section: { fontSize: 18, lineHeight: 24, fontWeight: '700', letterSpacing: 0 },
        card: { fontSize: 16, lineHeight: 22, fontWeight: '700', letterSpacing: 0 },
        body: { fontSize: 16, lineHeight: 24, fontWeight: '400', letterSpacing: 0 },
        label: { fontSize: 14, lineHeight: 20, fontWeight: '600', letterSpacing: 0.1 },
        caption: { fontSize: 12, lineHeight: 16, fontWeight: '400', letterSpacing: 0 },
        metric: { fontSize: 32, lineHeight: 38, fontWeight: '800', letterSpacing: -0.4 }
    },
    shape: {
        small: 8,
        medium: 12,
        large: 16,
        extraLarge: 24,
        sheet: 28,
        pill: 999
    },
    spacing: {
        extraSmall: 4,
        small: 8,
        medium: 12,
        large: 16,
        extraLarge: 24,
        jumbo: 32
    },
    interaction: {
        minimumTouchTarget: 48,
        focusRingWidth: 3,
        hoveredOpacity: 0.94,
        pressedOpacity: 0.86,
        disabledOpacity: 0.38,
        busyOpacity: 0.72
    },
    motion: {
        quick: 120,
        standard: 220
    }
} as const;

export type CalibrateColorScheme = keyof typeof calibrateDesignTokens.schemes;
export type CalibrateSemanticColors = typeof calibrateDesignTokens.schemes.light | typeof calibrateDesignTokens.schemes.dark;
